name: Sequential jobs 2
on: push
jobs:
  A:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 3 && echo "A"
  B:
    runs-on: ubuntu-latest
    needs: [A]
    steps:
      - run: sleep 3 && echo "B"
  C:
    runs-on: ubuntu-latest
    needs: [A]
    steps:
      - run: sleep 3 && echo "C"
  D:
    runs-on: ubuntu-latest
    needs: [B]
    steps:
      - run: sleep 3 && echo "D"
  E:
    runs-on: ubuntu-latest
    needs: [B]
    steps:
      - run: sleep 3 && echo "E"
  F:
    runs-on: ubuntu-latest
    needs: [C]
    steps:
      - run: sleep 3 && echo "F"
  G:
    runs-on: ubuntu-latest
    needs: [D,E,F]
    steps:
      - run: sleep 3 && echo "G"
